# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NetRequest_Demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NetRequest_Demo

pod 'AFNetworking', '~> 3.0.4'

  target 'NetRequest_DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NetRequest_DemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
